
INSERT INTO ada_prohibidas (cas_ph,nombre_ph)
VALUES(100516 ,'Benzyl alcohol '),(100527,'Benzaldehyde'),(101860,'Hexyl cinnamic aldehyde'),
(103413,'Benzyl cinnamate'),(103504,'Dibenzyl ether'),(103640,'Benzyl cinnamate'),(103797,'Phenyl acetone'),
(103957,'Cyclamen aldehyde'),(103694684,'2,2-Dimethyl-3-(3-tolyl)propan-1-ol'),
(104278,'Methyl anisylidene acetone'),(104541,'Cinnamic alcohol'),(104552,'Cinnamic aldehyde'),
(105135,'Anisyl alcohol'),(1331813,'Anisyl alcohol');

,(,'Cyclopentadecanolide'),(,'Citronellol'),(,'Citronellol'),(,'Citronellol'),
(,'Citronellol'),(,'Citronellol'),(,'Citronellol'),(,'Citronellal'),(,'Citronellal'),(,'Geraniol'),
(,'Hydroxycitronellal'),(,'3,3-Dimethyl-5-(2,2,3-trimethyl-3-cyclopenten-1-yl)-4-penten-2-ol'),
(,'Toluene'),(109-86-4,'Ethylene glycol monomethyl ether'),
(110-49-6,'Ethylene glycol monomethyl acetate'),(,'Cedrene'),(,'Cedrene'),
(,'Cedrene'),(,'Methyl heptine carbonate'),(111-28-4,'2,4-Hexadien-1-ol'),(,'Methyl octine carbonate'),
(,'2,6,6-Trimethylcyclohex-1,3-dienyl methanal'),(17102-64-6,'2,4-Hexadien-1-ol'),
(,'Methyl octine carbonate'),(,'2,6,6-Trimethylcyclohex-1,3-dienyl methanal'),(,'Musk moskene'),
(,'Benzyl salicylate'),(,'Dihydrocoumarin'),(,'Benzyl benzoate'),
(,'α-Methyl-1,3-benzodioxole-5-propionaldehyde (MMDHCA)'),(,'Cuminaldehyde'),
(,'Diphenylamine'),(,'α-Amyl cinnamic aldehyde'),(,'Benzylidene acetone'),(,'Phenylacetaldehyde'),
(,'p-Methoxybenzaldehyde'),(,'1-(2,4,4,5,5-Pentamethyl-1-cyclopenten-1-yl)ethan-1-one'),
(,'2-Nonyn-1-al dimethyl acetal'),(1335-46-2,'Methyl ionone'),
(127-42-4,'Methyl ionone'),( 127-43-5,'Methyl ionone'),(127-51-5,'Methyl ionone'),
(7779-30-8,'Methyl ionone'),(79-89-0,'Methyl ionone'),(1335-94-0,'Methyl ionone'),(,'Methyl ionone'),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),(,''),
