--PAISES

INSERT INTO ada_pais VALUES(1, 'AF', 'Afganistán','As');
INSERT INTO ada_pais VALUES(2, 'AX', 'Islas Aland','Eu');
INSERT INTO ada_pais VALUES(3, 'AL', 'Albania','Eu');
INSERT INTO ada_pais VALUES(4, 'DE', 'Alemania','Eu');
INSERT INTO ada_pais VALUES(5, 'AD', 'Andorra','Eu');
INSERT INTO ada_pais VALUES(6, 'AO', 'Angola','Af');
INSERT INTO ada_pais VALUES(7, 'AI', 'Anguilla','Amn');
INSERT INTO ada_pais VALUES(8, 'AQ', 'Antártida','Amn');
INSERT INTO ada_pais VALUES(9, 'AG', 'Antigua y Barbuda','Amn');
INSERT INTO ada_pais VALUES(10, 'AN', 'Antillas Holandesas','Ca');
INSERT INTO ada_pais VALUES(11, 'SA', 'Arabia Saudí','As');
INSERT INTO ada_pais VALUES(12, 'DZ', 'Argelia','Af');
INSERT INTO ada_pais VALUES(13, 'AR', 'Argentina','Ams');
INSERT INTO ada_pais VALUES(14, 'AM', 'Armenia','Eu');
INSERT INTO ada_pais VALUES(15, 'AW', 'Aruba','Ams');
INSERT INTO ada_pais VALUES(16, 'AU', 'Australia','Oc');
INSERT INTO ada_pais VALUES(17, 'AT', 'Austria','Eu');
INSERT INTO ada_pais VALUES(18, 'AZ', 'Azerbaiyán','Eu');
INSERT INTO ada_pais VALUES(19, 'BS', 'Bahamas','Amn');
INSERT INTO ada_pais VALUES(20, 'BH', 'Bahréin','As');
INSERT INTO ada_pais VALUES(21, 'BD', 'Bangladesh','As');
INSERT INTO ada_pais VALUES(22, 'BB', 'Barbados','Amn');
INSERT INTO ada_pais VALUES(23, 'BY', 'Bielorrusia','Eu');
INSERT INTO ada_pais VALUES(24, 'BE', 'Bélgica','Eu');
INSERT INTO ada_pais VALUES(25, 'BZ', 'Belice','Ca');
INSERT INTO ada_pais VALUES(26, 'BJ', 'Benin','Af');
INSERT INTO ada_pais VALUES(27, 'BM', 'Bermudas','Amn');
INSERT INTO ada_pais VALUES(28, 'BT', 'Bhután','As');
INSERT INTO ada_pais VALUES(29, 'BO', 'Bolivia','Ams');
INSERT INTO ada_pais VALUES(30, 'BA', 'Bosnia y Herzegovina','Eu');
INSERT INTO ada_pais VALUES(31, 'BW', 'Botsuana','Af');
INSERT INTO ada_pais VALUES(32, 'BV', 'Isla Bouvet','Oc');
INSERT INTO ada_pais VALUES(33, 'BR', 'Brasil','Ams');
INSERT INTO ada_pais VALUES(34, 'BN', 'Brunéi','As');
INSERT INTO ada_pais VALUES(35, 'BG', 'Bulgaria','Eu');
INSERT INTO ada_pais VALUES(36, 'BF', 'Burkina Faso','Af');
INSERT INTO ada_pais VALUES(37, 'BI', 'Burundi','Af');
INSERT INTO ada_pais VALUES(38, 'CV', 'Cabo Verde','Af');
INSERT INTO ada_pais VALUES(39, 'KY', 'Islas Caimán','Amn');
INSERT INTO ada_pais VALUES(40, 'KH', 'Camboya','As');
INSERT INTO ada_pais VALUES(41, 'CM', 'Camerún','Af');
INSERT INTO ada_pais VALUES(42, 'CA', 'Canadá','Amn');
INSERT INTO ada_pais VALUES(43, 'CF', 'República Centroafricana','Af');
INSERT INTO ada_pais VALUES(44, 'TD', 'Chad','Af');
INSERT INTO ada_pais VALUES(45, 'CZ', 'República Checa','Eu');
INSERT INTO ada_pais VALUES(46, 'CL', 'Chile','Ams');
INSERT INTO ada_pais VALUES(47, 'CN', 'China','As');
INSERT INTO ada_pais VALUES(48, 'CY', 'Chipre','Eu');
INSERT INTO ada_pais VALUES(49, 'CX', 'Isla de Navidad','Oc');
INSERT INTO ada_pais VALUES(50, 'VA', 'Ciudad del Vaticano','Eu');
INSERT INTO ada_pais VALUES(51, 'CC', 'Islas Cocos','As');
INSERT INTO ada_pais VALUES(52, 'CO', 'Colombia','Ams');
INSERT INTO ada_pais VALUES(53, 'KM', 'Comores','Af');
INSERT INTO ada_pais VALUES(54, 'CD', 'República Democrática del Congo','Af');
INSERT INTO ada_pais VALUES(55, 'CG', 'Congo','Af');
INSERT INTO ada_pais VALUES(56, 'CK', 'Islas Cook','Oc');
INSERT INTO ada_pais VALUES(57, 'KP', 'Corea del Norte','As');
INSERT INTO ada_pais VALUES(58, 'KR', 'Corea del Sur','As');
INSERT INTO ada_pais VALUES(59, 'CI', 'Costa de Marfil','Af');
INSERT INTO ada_pais VALUES(60, 'CR', 'Costa Rica','Ca');
INSERT INTO ada_pais VALUES(61, 'HR', 'Croacia','Eu');
INSERT INTO ada_pais VALUES(62, 'CU', 'Cuba','Amn');
INSERT INTO ada_pais VALUES(63, 'DK', 'Dinamarca','Eu');
INSERT INTO ada_pais VALUES(64, 'DM', 'Dominica','Amn');
INSERT INTO ada_pais VALUES(65, 'DO', 'República Dominicana','Amn');
INSERT INTO ada_pais VALUES(66, 'EC', 'Ecuador','Ams');
INSERT INTO ada_pais VALUES(67, 'EG', 'Egipto','Af');
INSERT INTO ada_pais VALUES(68, 'SV', 'El Salvador','Ca');
INSERT INTO ada_pais VALUES(69, 'AE', 'Emiratos Árabes Unidos','As');
INSERT INTO ada_pais VALUES(70, 'ER', 'Eritrea','Af');
INSERT INTO ada_pais VALUES(71, 'SK', 'Eslovaquia','Eu');
INSERT INTO ada_pais VALUES(72, 'SI', 'Eslovenia','Eu');
INSERT INTO ada_pais VALUES(73, 'ES', 'España','Eu');
INSERT INTO ada_pais VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos','Amn');
INSERT INTO ada_pais VALUES(75, 'US', 'Estados Unidos','Amn');
INSERT INTO ada_pais VALUES(76, 'EE', 'Estonia','Eu');
INSERT INTO ada_pais VALUES(77, 'ET', 'Etiopía','Af');
INSERT INTO ada_pais VALUES(78, 'FO', 'Islas Feroe','Eu');
INSERT INTO ada_pais VALUES(79, 'PH', 'Filipinas','As');
INSERT INTO ada_pais VALUES(80, 'FI', 'Finlandia','Eu');
INSERT INTO ada_pais VALUES(81, 'FJ', 'Fiji','Oc');
INSERT INTO ada_pais VALUES(82, 'FR', 'Francia','Eu');
INSERT INTO ada_pais VALUES(83, 'GA', 'Gabón','Af');
INSERT INTO ada_pais VALUES(84, 'GM', 'Gambia','Af');
INSERT INTO ada_pais VALUES(85, 'GE', 'Georgia','Eu');
INSERT INTO ada_pais VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur','Ams');
INSERT INTO ada_pais VALUES(87, 'GH', 'Ghana','Af');
INSERT INTO ada_pais VALUES(88, 'GI', 'Gibraltar','Eu');
INSERT INTO ada_pais VALUES(89, 'GD', 'Granada','Amn');
INSERT INTO ada_pais VALUES(90, 'GR', 'Grecia','Eu');
INSERT INTO ada_pais VALUES(91, 'GL', 'Groenlandia','Amn');
INSERT INTO ada_pais VALUES(92, 'GP', 'Guadalupe','Amn');
INSERT INTO ada_pais VALUES(93, 'GU', 'Guam','Oc');
INSERT INTO ada_pais VALUES(94, 'GT', 'Guatemala','Ca');
INSERT INTO ada_pais VALUES(95, 'GF', 'Guayana Francesa','Ams');
INSERT INTO ada_pais VALUES(96, 'GN', 'Guinea','Af');
INSERT INTO ada_pais VALUES(97, 'GQ', 'Guinea Ecuatorial','Af');
INSERT INTO ada_pais VALUES(98, 'GW', 'Guinea-Bissau','Af');
INSERT INTO ada_pais VALUES(99, 'GY', 'Guyana','Ams');
INSERT INTO ada_pais VALUES(100, 'HT', 'Haití','Amn');
INSERT INTO ada_pais VALUES(101, 'HM', 'Islas Heard y McDonald','Oc');
INSERT INTO ada_pais VALUES(102, 'HN', 'Honduras','Ca');
INSERT INTO ada_pais VALUES(103, 'HK', 'Hong Kong','As');
INSERT INTO ada_pais VALUES(104, 'HU', 'Hungría','Eu');
INSERT INTO ada_pais VALUES(105, 'IN', 'India','As');
INSERT INTO ada_pais VALUES(106, 'ID', 'Indonesia','As');
INSERT INTO ada_pais VALUES(107, 'IR', 'Irán','As');
INSERT INTO ada_pais VALUES(108, 'IQ', 'Iraq','As');
INSERT INTO ada_pais VALUES(109, 'IE', 'Irlanda','Eu');
INSERT INTO ada_pais VALUES(110, 'IS', 'Islandia','Eu');
INSERT INTO ada_pais VALUES(111, 'IL', 'Israel','As');
INSERT INTO ada_pais VALUES(112, 'IT', 'Italia','Eu');
INSERT INTO ada_pais VALUES(113, 'JM', 'Jamaica','Amn');
INSERT INTO ada_pais VALUES(114, 'JP', 'Japón','As');
INSERT INTO ada_pais VALUES(115, 'JO', 'Jordania','As');
INSERT INTO ada_pais VALUES(116, 'KZ', 'Kazajistán','As');
INSERT INTO ada_pais VALUES(117, 'KE', 'Kenia','Af');
INSERT INTO ada_pais VALUES(118, 'KG', 'Kirguistán','As');
INSERT INTO ada_pais VALUES(119, 'KI', 'Kiribati','Oc');
INSERT INTO ada_pais VALUES(120, 'KW', 'Kuwait','As');
INSERT INTO ada_pais VALUES(121, 'LA', 'Laos','As');
INSERT INTO ada_pais VALUES(122, 'LS', 'Lesotho','Af');
INSERT INTO ada_pais VALUES(123, 'LV', 'Letonia','Eu');
INSERT INTO ada_pais VALUES(124, 'LB', 'Líbano','As');
INSERT INTO ada_pais VALUES(125, 'LR', 'Liberia','Af');
INSERT INTO ada_pais VALUES(126, 'LY', 'Libia','Af');
INSERT INTO ada_pais VALUES(127, 'LI', 'Liechtenstein','Eu');
INSERT INTO ada_pais VALUES(128, 'LT', 'Lituania','Eu');
INSERT INTO ada_pais VALUES(129, 'LU', 'Luxemburgo','Eu');
INSERT INTO ada_pais VALUES(130, 'MO', 'Macao','As');
INSERT INTO ada_pais VALUES(131, 'MK', 'ARY Macedonia','Eu');
INSERT INTO ada_pais VALUES(132, 'MG', 'Madagascar','Af');
INSERT INTO ada_pais VALUES(133, 'MY', 'Malasia','As');
INSERT INTO ada_pais VALUES(134, 'MW', 'Malawi','Af');
INSERT INTO ada_pais VALUES(135, 'MV', 'Maldivas','As');
INSERT INTO ada_pais VALUES(136, 'ML', 'Malí','Af');
INSERT INTO ada_pais VALUES(137, 'MT', 'Malta','Eu');
INSERT INTO ada_pais VALUES(138, 'FK', 'Islas Malvinas','Oc');
INSERT INTO ada_pais VALUES(139, 'MP', 'Islas Marianas del Norte','Oc');
INSERT INTO ada_pais VALUES(140, 'MA', 'Marruecos','Af');
INSERT INTO ada_pais VALUES(141, 'MH', 'Islas Marshall','Oc');
INSERT INTO ada_pais VALUES(142, 'MQ', 'Martinica','Amn');
INSERT INTO ada_pais VALUES(143, 'MU', 'Mauricio','Af');
INSERT INTO ada_pais VALUES(144, 'MR', 'Mauritania','Af');
INSERT INTO ada_pais VALUES(145, 'YT', 'Mayotte','Af');
INSERT INTO ada_pais VALUES(146, 'MX', 'México','Ca');
INSERT INTO ada_pais VALUES(147, 'FM', 'Micronesia','Oc');
INSERT INTO ada_pais VALUES(148, 'MD', 'Moldavia','Eu');
INSERT INTO ada_pais VALUES(149, 'MC', 'Mónaco','Eu');
INSERT INTO ada_pais VALUES(150, 'MN', 'Mongolia','As');
INSERT INTO ada_pais VALUES(151, 'MS', 'Montserrat','Eu');
INSERT INTO ada_pais VALUES(152, 'MZ', 'Mozambique','Af');
INSERT INTO ada_pais VALUES(153, 'MM', 'Myanmar','As');
INSERT INTO ada_pais VALUES(154, 'NA', 'Namibia','Af');
INSERT INTO ada_pais VALUES(155, 'NR', 'Nauru','Oc');
INSERT INTO ada_pais VALUES(156, 'NP', 'Nepal','As');
INSERT INTO ada_pais VALUES(157, 'NI', 'Nicaragua','Ca');
INSERT INTO ada_pais VALUES(158, 'NE', 'Níger','Af');
INSERT INTO ada_pais VALUES(159, 'NG', 'Nigeria','Af');
INSERT INTO ada_pais VALUES(160, 'NU', 'Niue','Oc');
INSERT INTO ada_pais VALUES(161, 'NF', 'Isla Norfolk','Oc');
INSERT INTO ada_pais VALUES(162, 'NO', 'Noruega','Eu');
INSERT INTO ada_pais VALUES(163, 'NC', 'Nueva Caledonia','Oc');
INSERT INTO ada_pais VALUES(164, 'NZ', 'Nueva Zelanda','Oc');
INSERT INTO ada_pais VALUES(165, 'OM', 'Omán','As');
INSERT INTO ada_pais VALUES(166, 'NL', 'Países Bajos','Eu');
INSERT INTO ada_pais VALUES(167, 'PK', 'Pakistán','As');
INSERT INTO ada_pais VALUES(168, 'PW', 'Palau','Oc');
INSERT INTO ada_pais VALUES(169, 'PS', 'Palestina','As');
INSERT INTO ada_pais VALUES(170, 'PA', 'Panamá','Ca');
INSERT INTO ada_pais VALUES(171, 'PG', 'Papúa Nueva Guinea','Oc');
INSERT INTO ada_pais VALUES(172, 'PY', 'Paraguay','Ams');
INSERT INTO ada_pais VALUES(173, 'PE', 'Perú','Ams');
INSERT INTO ada_pais VALUES(174, 'PN', 'Islas Pitcairn','Oc');
INSERT INTO ada_pais VALUES(175, 'PF', 'Polinesia Francesa','Oc');
INSERT INTO ada_pais VALUES(176, 'PL', 'Polonia','Eu');
INSERT INTO ada_pais VALUES(177, 'PT', 'Portugal','Eu');
INSERT INTO ada_pais VALUES(178, 'PR', 'Puerto Rico','Amn');
INSERT INTO ada_pais VALUES(179, 'QA', 'Qatar','As');
INSERT INTO ada_pais VALUES(180, 'GB', 'Reino Unido','Eu');
INSERT INTO ada_pais VALUES(181, 'RE', 'Reunión','Af');
INSERT INTO ada_pais VALUES(182, 'RW', 'Ruanda','Af');
INSERT INTO ada_pais VALUES(183, 'RO', 'Rumania','Eu');
INSERT INTO ada_pais VALUES(184, 'RU', 'Rusia','Eu');
INSERT INTO ada_pais VALUES(185, 'EH', 'Sahara Occidental','Af');
INSERT INTO ada_pais VALUES(186, 'SB', 'Islas Salomón','Oc');
INSERT INTO ada_pais VALUES(187, 'WS', 'Samoa','Oc');
INSERT INTO ada_pais VALUES(188, 'AS', 'Samoa Americana','Oc');
INSERT INTO ada_pais VALUES(189, 'KN', 'San Cristóbal y Nieves','Amn');
INSERT INTO ada_pais VALUES(190, 'SM', 'San Marino','Eu');
INSERT INTO ada_pais VALUES(191, 'PM', 'San Pedro y Miquelón','Amn');
INSERT INTO ada_pais VALUES(192, 'VC', 'San Vicente y las Granadinas','Amn');
INSERT INTO ada_pais VALUES(193, 'SH', 'Santa Helena','Af');
INSERT INTO ada_pais VALUES(194, 'LC', 'Santa Lucía','Amn');
INSERT INTO ada_pais VALUES(195, 'ST', 'Santo Tomé y Príncipe','Af');
INSERT INTO ada_pais VALUES(196, 'SN', 'Senegal','Af');
INSERT INTO ada_pais VALUES(197, 'CS', 'Serbia y Montenegro','Eu');
INSERT INTO ada_pais VALUES(198, 'SC', 'Seychelles','Af');
INSERT INTO ada_pais VALUES(199, 'SL', 'Sierra Leona','Af');
INSERT INTO ada_pais VALUES(200, 'SG', 'Singapur','As');
INSERT INTO ada_pais VALUES(201, 'SY', 'Siria','As');
INSERT INTO ada_pais VALUES(202, 'SO', 'Somalia','Af');
INSERT INTO ada_pais VALUES(203, 'LK', 'Sri Lanka','As');
INSERT INTO ada_pais VALUES(204, 'SZ', 'Suazilandia','Af');
INSERT INTO ada_pais VALUES(205, 'ZA', 'Sudáfrica','Af');
INSERT INTO ada_pais VALUES(206, 'SD', 'Sudán','Af');
INSERT INTO ada_pais VALUES(207, 'SE', 'Suecia','Eu');
INSERT INTO ada_pais VALUES(208, 'CH', 'Suiza','Eu');
INSERT INTO ada_pais VALUES(209, 'SR', 'Surinam','Ams');
INSERT INTO ada_pais VALUES(210, 'SJ', 'Svalbard y Jan Mayen','Eu');
INSERT INTO ada_pais VALUES(211, 'TH', 'Tailandia','As');
INSERT INTO ada_pais VALUES(212, 'TW', 'Taiwán','As');
INSERT INTO ada_pais VALUES(213, 'TZ', 'Tanzania','Af');
INSERT INTO ada_pais VALUES(214, 'TJ', 'Tayikistán','As');
INSERT INTO ada_pais VALUES(215, 'IO', 'Territorio Británico del Océano Índico','As');
INSERT INTO ada_pais VALUES(216, 'TF', 'Territorios Australes Franceses','Eu');
INSERT INTO ada_pais VALUES(217, 'TL', 'Timor Oriental','As');
INSERT INTO ada_pais VALUES(218, 'TG', 'Togo','Af');
INSERT INTO ada_pais VALUES(219, 'TK', 'Tokelau','Oc');
INSERT INTO ada_pais VALUES(220, 'TO', 'Tonga','Oc');
INSERT INTO ada_pais VALUES(221, 'TT', 'Trinidad y Tobago','Ams');
INSERT INTO ada_pais VALUES(222, 'TN', 'Túnez','Af');
INSERT INTO ada_pais VALUES(223, 'TC', 'Islas Turcas y Caicos','Amn');
INSERT INTO ada_pais VALUES(224, 'TM', 'Turkmenistán','As');
INSERT INTO ada_pais VALUES(225, 'TR', 'Turquía','Eu');
INSERT INTO ada_pais VALUES(226, 'TV', 'Tuvalu','Oc');
INSERT INTO ada_pais VALUES(227, 'UA', 'Ucrania','Eu');
INSERT INTO ada_pais VALUES(228, 'UG', 'Uganda','Af');
INSERT INTO ada_pais VALUES(229, 'UY', 'Uruguay','Ams');
INSERT INTO ada_pais VALUES(230, 'UZ', 'Uzbekistán','As');
INSERT INTO ada_pais VALUES(231, 'VU', 'Vanuatu','Oc');
INSERT INTO ada_pais VALUES(232, 'VE', 'Venezuela','Ams');
INSERT INTO ada_pais VALUES(233, 'VN', 'Vietnam','As');
INSERT INTO ada_pais VALUES(234, 'VG', 'Islas Vírgenes Británicas','Amn');
INSERT INTO ada_pais VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos','Amn');
INSERT INTO ada_pais VALUES(236, 'WF', 'Wallis y Futuna','Oc');
INSERT INTO ada_pais VALUES(237, 'YE', 'Yemen','As');
INSERT INTO ada_pais VALUES(238, 'DJ', 'Yibuti','Af');
INSERT INTO ada_pais VALUES(239, 'ZM', 'Zambia','Af');
INSERT INTO ada_pais VALUES(240, 'ZW', 'Zimbabue','Af');


--Familias Olfativas

INSERT INTO ada_familia_olfativa (nombre_familia)
values('Verde'),('Cítrico'),('Flores'),('Frutas'),('Aromáticos'),('Helechos'),
('Chipe'),('Maderas'),('Orientales'),('Otros');

--
